version: '3.6'
services:
  api:
    container_name: Todo-App
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8050:8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tododb?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - db
    networks:
      - esnet
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: tododb
        # So you don't have to use root, but you can if you like
      MYSQL_USER: user
      # You can use whatever password you like
      MYSQL_PASSWORD: pass
      # Password for root access
      MYSQL_ROOT_PASSWORD: pass
    ports:
       - 3308:3306
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - esnet
volumes:
  my-db:
networks:
  esnet: